# Generated by Django 4.2.6 on 2023-10-18 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='categoryImg')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='productImg')),
                ('hover_image', models.ImageField(blank=True, null=True, upload_to='productImg')),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('product_purchase_price', models.IntegerField(blank=True, null=True)),
                ('sort_description', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=300)),
                ('additional_description', models.CharField(blank=True, max_length=300, null=True)),
                ('stock_quentity', models.PositiveIntegerField()),
                ('categoris', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.productcategory', verbose_name='product Category')),
            ],
        ),
    ]
